Repository connect-foundation/2019-12, pull requests merged in 2019-12, with the labels that each got.

#170 [PR] useFetch 개선
  client/src/hooks/base/useFetch/index.spec.tsx
  client/src/hooks/base/useFetch/index.ts
Labels: ✨ Feature, 🌕 Frontend

#160 [PR] 중복되는 Template(BasicPage -> BasedTemplate) 제거
  client/src/pages/BasicPage/templates/index.stories.tsx
  client/src/pages/BasicPage/templates/index.tsx
  client/src/pages/BasicPage/templates/style.ts
Labels: 🌕 Frontend, 🚨 ASAP, 🧩 Component

#158 [PR] Health Check를 할 수 있는 라우터를 만듦
  server/src/app.ts
Labels: 🌑 Backend

#178 [PR] 폰트 수정 로고 변경
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/src/assets/img/logo-gray.svg
  client/src/assets/img/logo.svg
  client/src/commons/style/GlobalStyle.ts
  client/src/components/organisms/MainBanner/index.tsx
  client/src/components/organisms/MainBanner/style.ts
Labels: 🌕 Frontend

#169 [PR] EventDetail (이벤트상세) 리팩토링
  client/src/components/atoms/Icon/index.tsx
  client/src/components/atoms/Price/__snapshots__/index.spec.tsx.snap
  client/src/components/atoms/Price/index.spec.tsx
  client/src/components/atoms/Price/index.stories.tsx
  client/src/components/atoms/Price/index.tsx
  client/src/components/atoms/Price/style.ts
  client/src/components/molecules/IconLabel/__snapshots__/index.spec.tsx.snap
  client/src/components/molecules/IconLabel/index.spec.tsx
  client/src/components/molecules/IconLabel/index.stories.tsx
  client/src/components/molecules/IconLabel/index.tsx
  client/src/components/molecules/IconLabel/style.ts
  client/src/components/organisms/EventHeader/index.stories.tsx
  client/src/components/organisms/EventHeader/index.tsx
  client/src/components/organisms/EventHeader/style.ts
  client/src/components/organisms/Place/index.stories.tsx
  client/src/components/organisms/Place/index.tsx
  client/src/components/organisms/Place/style.ts
  client/src/components/organisms/Ticket/__snapshots__/indes.spec.tsx.snap
  client/src/components/organisms/Ticket/indes.spec.tsx
  client/src/components/organisms/Ticket/index.stories.tsx
  client/src/components/organisms/Ticket/index.tsx
  client/src/components/organisms/Ticket/style.ts
  client/src/pages/EventDetail/index.stories.tsx
  client/src/pages/EventDetail/index.tsx
  client/src/pages/EventDetail/store.tsx
  client/src/pages/EventDetail/template/index.stories.tsx
  client/src/pages/EventDetail/template/index.tsx
  client/src/pages/EventDetail/template/style.ts
  client/src/pages/EventDetail/view.tsx
  client/src/types/Data.ts
  client/src/types/States.ts
  client/src/utils/currencyDecorator.spec.ts
  client/src/utils/currencyDecorator.ts
Labels: ✨ Feature, 🌕 Frontend

#175 [PR] EventDate (이벤트 일시)
  client/src/components/atoms/EventDate/__snapshots__/indes.spec.tsx.snap
  client/src/components/atoms/EventDate/indes.spec.tsx
  client/src/components/atoms/EventDate/index.stories.tsx
  client/src/components/atoms/EventDate/index.tsx
  client/src/components/atoms/EventDate/style.ts
  client/src/utils/dateCalculator.spec.ts
  client/src/utils/dateCalculator.ts
Labels: ✨ Feature, 🌕 Frontend, 🧩 Component

#173 [PR] 전역 Store를 만듦, Header에 로그인 상태가 표시되도록 이를 사용할 수 있게 함. / 회원가입과 로그인을 Account Store와 연결함.
  client/src/App.tsx
  client/src/commons/constants/routes.ts
  client/src/components/organisms/Header/index.stories.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/hooks/index.ts
  client/src/hooks/meta/accountReducer/index.ts
  client/src/pages/BasedTemplate/templates/index.tsx
  client/src/pages/Login/index.tsx
  client/src/pages/SignUp/store.tsx
  client/src/pages/SignUp/view.tsx
  client/src/stores/accountStore.tsx
  client/src/stores/afterLoginStore.tsx
  client/src/stores/index.tsx
  client/src/types/Actions.ts
  client/src/types/CustomHooks.ts
  client/src/types/Data.ts
  client/src/types/States.ts
  server/src/routes/api/auth/controllers/authCallback.ts
  server/src/routes/api/auth/controllers/authToken.ts
  server/src/routes/api/users/controllers/createUser.ts
  server/src/routes/api/users/controllers/getUser.ts
  server/src/routes/api/users/controllers/index.ts
  server/src/routes/api/users/index.ts
  server/src/services/index.ts
  server/src/services/users.ts
  server/src/utils/jwt.ts
  server/src/utils/passport.ts
Labels: 🌑 Backend, 🌕 Frontend, 🕊 API

#186 [PR] DB 모델 수정
  client/src/components/organisms/CardGrid/index.stories.tsx
  client/src/components/organisms/CardGrid/index.tsx
  client/src/components/organisms/EventHeader/index.stories.tsx
  client/src/components/organisms/EventHeader/index.tsx
  client/src/pages/EventDetail/store.tsx
  client/src/pages/EventDetail/view.tsx
  client/src/types/Data.ts
  client/src/types/Event.ts
  server/db_seeds/events.json
  server/db_seeds/orders.json
  server/db_seeds/ticketSubscription.json
  server/db_seeds/ticketTypes.json
  server/db_seeds/userTickets.json
  server/src/models/Event.ts
  server/src/models/OrderTicket.ts
  server/src/models/TicketSubscription.ts
  server/src/models/TicketType.ts
  server/src/models/User.ts
  server/src/models/UserTicket.ts
  server/src/models/index.ts
  server/src/utils/sequelize.ts
  server/test/db/__snapshots__/seed.spec.ts.snap
  server/test/db/model.spec.ts
  server/test/db/seed.spec.ts
Labels: 🌑 Backend, 📚 Database

#188 [PR] PR 템플릿 수정 제안합니다.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 👷‍♀️ Enviornment, 💡Optional

#192 [PR] 이벤트 모델에서 위도 경도 추가
  server/src/models/Event.ts
  server/test/db/__snapshots__/seed.spec.ts.snap
Labels: 🌑 Backend, 📚 Database

#190 [PR] 버튼 컴포넌트 리팩토링 및 워닝 제거
  client/src/components/atoms/Btn/__snapshots__/index.spec.tsx.snap
  client/src/components/atoms/Btn/index.spec.tsx
  client/src/components/atoms/Btn/index.stories.tsx
  client/src/components/atoms/Btn/index.tsx
  client/src/components/atoms/Btn/style.ts
  client/src/components/molecules/IconBtn/__snapshots__/index.spec.tsx.snap
  client/src/components/organisms/EventHeader/index.tsx
  client/src/components/organisms/Header/index.stories.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/components/organisms/MainBanner/index.tsx
  client/src/components/organisms/SignUpForm/index.stories.tsx
  client/src/pages/SignUp/view.tsx
Labels: 🌕 Frontend, 🐛 BUG, 🧩 Component

#202 [PR] GET /event/:eventId 리팩토링
  server/package.json
  server/src/routes/api/events/controllers/getEvent.ts
  server/src/routes/api/events/index.ts
  server/src/routes/api/events/middlewares/index.ts
  server/src/routes/api/events/middlewares/requestParamHandler.ts
  server/src/types/express/index.d.ts
  server/test/api/event.spec.ts
  server/tsc.args
  server/tsconfig.json
Labels: 🌑 Backend, 🕊 API

#204 [PR] Travis pre_deploy stage 추가
  .travis.yml
  reserve-server/src/routes/api/controllers/authUser.ts
Labels: 🌈 DevOps, 🚨 ASAP

#199 [PR] Img, ImgBtn 구현
  client/src/components/atoms/GoogleMap/index.tsx
  client/src/components/atoms/GoogleMap/style.ts
  client/src/components/atoms/Icon/index.tsx
  client/src/components/atoms/Img/__snapshots__/index.spec.tsx.snap
  client/src/components/atoms/Img/index.spec.tsx
  client/src/components/atoms/Img/index.stories.tsx
  client/src/components/atoms/Img/index.tsx
  client/src/components/atoms/Img/style.ts
  client/src/components/molecules/Card/index.tsx
  client/src/components/molecules/Card/style.ts
  client/src/components/molecules/ImgBtn/__snapshots__/index.spec.tsx.snap
  client/src/components/molecules/ImgBtn/index.spec.tsx
  client/src/components/molecules/ImgBtn/index.stories.tsx
  client/src/components/molecules/ImgBtn/index.tsx
  client/src/components/molecules/ImgBtn/style.ts
  client/src/components/organisms/Header/index.tsx
  client/src/components/organisms/Header/style.ts
  client/src/components/organisms/MainBanner/index.tsx
  client/src/pages/SignUp/template/style.ts
  client/src/pages/SignUp/view.tsx
Labels: 🌕 Frontend, 🧩 Component

#198 [PR] 로그인, 회원가입, 메인, 이벤트 상세 E2E 테스트
  .env.production.enc
  .gitignore
  .travis.yml
  client/.eslintrc.json
  client/cypress.json
  client/cypress/fixtures/event.json
  client/cypress/fixtures/events.json
  client/cypress/integration/bookus-sample.spec.tsx
  client/cypress/integration/eventdetail.spec.ts
  client/cypress/integration/header.spec.ts
  client/cypress/integration/login.spec.ts
  client/cypress/integration/main.spec.ts
  client/cypress/integration/signup.spec.ts
  client/cypress/plugins/index.js
  client/cypress/support/index.js
  client/cypress/tsconfig.json
  client/cypress/webpack.config.js
  client/package.json
  client/src/components/molecules/Card/index.tsx
  client/src/components/molecules/FormInput/index.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/components/organisms/SignUpForm/index.tsx
  client/src/pages/SignUp/view.tsx
  secrets.tar.enc
  yarn.lock
Labels: 🌕 Frontend, 🏃‍♂️Test

#195 [PR] 이벤트 디테일 구글맵
  client/src/components/atoms/GoogleMap/index.stories.tsx
  client/src/components/atoms/GoogleMap/index.tsx
  client/src/components/organisms/Place/index.stories.tsx
  client/src/components/organisms/Place/index.tsx
  client/src/pages/EventDetail/store.tsx
  client/src/pages/EventDetail/view.tsx
  client/src/types/Data.ts
Labels: ✨ Feature, 🌕 Frontend, 🧩 Component

#205 [PR] GET events/:eventId/tickets
  server/src/routes/api/events/controllers/getEventTickets.ts
  server/src/routes/api/events/controllers/index.ts
  server/src/routes/api/events/index.ts
  server/test/api/event.spec.ts
Labels: 🌑 Backend, 🕊 API

#206 [PR] http 상태코드를 http-status 모듈을 이용하여 개선
  client/package.json
  client/src/hooks/base/useFetch/index.spec.tsx
  client/src/hooks/base/useFetch/index.ts
  reserve-server/package.json
  reserve-server/src/routes/api/controllers/authUser.ts
  reserve-server/src/routes/api/controllers/checkTicket.ts
  reserve-server/src/routes/api/controllers/orderTicket.ts
  reserve-server/src/utils/errorHandler.ts
  reserve-server/test/api.spec.ts
  server/package.json
  server/src/routes/api/events/middlewares/requestParamHandler.ts
  server/src/routes/api/users/controllers/createUser.ts
  server/src/utils/errorHandler.ts
  server/test/api/event.spec.ts
  yarn.lock
Labels: 🌑 Backend

#209 [PR] GET /events/coordinate
  server/package.json
  server/src/routes/api/events/controllers/convertPlaceToCoordinate.ts
  server/src/routes/api/events/controllers/index.ts
  server/src/routes/api/events/index.ts
  server/src/services/events.ts
  server/test/api/event.spec.ts
  yarn.lock
Labels: 🌑 Backend, 🕊 API

#212 [1차 PR] EventJoin(이벤트 예약 페이지)
  .travis.yml
  client/src/App.tsx
  client/src/assets/img/left-arrow.svg
  client/src/assets/img/right-arrow.svg
  client/src/assets/img/ticket.svg
  client/src/components/molecules/Counter/index.stories.tsx
  client/src/components/molecules/Counter/index.tsx
  client/src/components/molecules/Counter/style.ts
  client/src/components/organisms/EventHeader/index.stories.tsx
  client/src/components/organisms/EventHeader/index.tsx
  client/src/components/organisms/Place/index.stories.tsx
  client/src/components/organisms/Place/index.tsx
  client/src/components/organisms/TicketBox/index.stories.tsx
  client/src/components/organisms/TicketBox/index.tsx
  client/src/components/organisms/TicketBox/style.ts
  client/src/pages/EventDetail/store.tsx
  client/src/pages/EventDetail/view.tsx
  client/src/pages/EventJoin/index.tsx
  client/src/pages/EventJoin/store.tsx
  client/src/pages/EventJoin/style.ts
  client/src/pages/EventJoin/template/index.tsx
  client/src/pages/EventJoin/template/style.ts
  client/src/pages/EventJoin/view.tsx
  client/src/types/Data.ts
  client/src/utils/dateCalculator.ts
  secrets.tar.enc
Labels: ✨ Feature, 🌕 Frontend, 😏 Page

#174 [PR] 메인페이지 리팩토링
  client/src/commons/constants/number.ts
  client/src/components/molecules/Card/index.tsx
  client/src/components/organisms/CardGrid/index.tsx
  client/src/components/organisms/CardGrid/style.ts
  client/src/hooks/base/useIntersect/index.ts
  client/src/pages/Main/index.tsx
  client/src/utils/delay.ts
Labels: 🌕 Frontend, 😏 Page

#218 [PR] 404 NOT FOUND
  client/src/App.tsx
  client/src/pages/NotFound/index.stories.tsx
  client/src/pages/NotFound/index.tsx
  client/src/pages/NotFound/template/index.tsx
  client/src/pages/NotFound/template/style.ts
Labels: 🌕 Frontend, 😏 Page

#215 [2차 PR] EventJoinPage (이벤트 예약)
  client/.env.template
  client/src/pages/EventJoin/view.tsx
Labels: ✨ Feature, 🌕 Frontend, 😏 Page

#217 [PR] 이벤트 주최하기 라우팅 버그 해결
  client/src/commons/constants/routes.ts
  client/src/components/organisms/CardGrid/index.tsx
Labels: 🌕 Frontend, 🐛 BUG, 🚨 ASAP

#211 [PR] sequelize whereOptions 타입추가
  reserve-server/src/services/ticketType.ts
  reserve-server/src/services/userTicket.ts
  server/src/services/users.ts
Labels: 🌑 Backend

#219 [PR] flatten location in EventDetail interface
  client/src/pages/EventDetail/store.tsx
  client/src/pages/EventDetail/view.tsx
  client/src/types/Data.ts
Labels: 🌕 Frontend, 🚨 ASAP

#227 [PR] EventDetailPage(이벤트 상세) width 수정
  client/src/pages/EventDetail/template/index.tsx
  client/src/pages/EventDetail/template/style.ts
  client/src/pages/EventDetail/view.tsx
Labels: 🌕 Frontend, 🐛 BUG

#229 [PR] 스토리북 실행 시 SignUp Knob이 바로 표시되는 현상 해결
  client/src/components/organisms/SignUpForm/index.stories.tsx
Labels: 🌕 Frontend, 🐛 BUG

#243 [PR] Live / Build 환경 Storybook에서 GoogleMap 이 표시되지 않는 현상 해결
  client/src/components/atoms/GoogleMap/index.tsx
Labels: 🌕 Frontend, 🐛 BUG

#245 [PR] Client util 모듈들을 index와 directory로 분리
  client/src/pages/SignUp/store.tsx
  client/src/utils/currencyDecorator/index.spec.ts
  client/src/utils/currencyDecorator/index.ts
  client/src/utils/dateCalculator/index.spec.ts
  client/src/utils/dateCalculator/index.ts
  client/src/utils/delay/index.ts
  client/src/utils/validateInput/index.spec.ts
  client/src/utils/validateInput/index.ts
Labels: 🌕 Frontend

#247 [PR] 구글맵 draggable false
  client/src/components/atoms/GoogleMap/index.tsx
Labels: 🌕 Frontend, 🐛 BUG

#248 [PR] Client import style 변경(YH + JH style)
  client/src/components/atoms/GoogleMap/index.tsx
  client/src/components/atoms/GoogleMap/style.ts
  client/src/components/atoms/Icon/index.spec.tsx
  client/src/components/atoms/Icon/index.stories.tsx
  client/src/components/atoms/Icon/index.tsx
  client/src/components/atoms/Img/index.tsx
  client/src/components/index.ts
  client/src/components/molecules/Card/index.tsx
  client/src/components/molecules/Counter/index.tsx
  client/src/components/molecules/FormInput/index.tsx
  client/src/components/molecules/FormInput/style.ts
  client/src/components/molecules/IconBtn/index.spec.tsx
  client/src/components/molecules/IconBtn/index.stories.tsx
  client/src/components/molecules/IconBtn/style.ts
  client/src/components/molecules/IconLabel/index.spec.tsx
  client/src/components/molecules/IconLabel/index.stories.tsx
  client/src/components/molecules/IconLabel/index.tsx
  client/src/components/molecules/ImgBtn/index.tsx
  client/src/components/molecules/ImgBtn/style.ts
  client/src/components/organisms/CardGrid/index.stories.tsx
  client/src/components/organisms/CardGrid/index.tsx
  client/src/components/organisms/EventHeader/index.tsx
  client/src/components/organisms/EventHeader/style.ts
  client/src/components/organisms/Footer/index.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/components/organisms/Header/style.ts
  client/src/components/organisms/MainBanner/index.tsx
  client/src/components/organisms/Place/index.tsx
  client/src/components/organisms/SignUpForm/index.stories.tsx
  client/src/components/organisms/SignUpForm/index.tsx
  client/src/components/organisms/SignUpForm/style.ts
  client/src/components/organisms/Ticket/__snapshots__/indes.spec.tsx.snap
  client/src/components/organisms/Ticket/index.tsx
  client/src/components/organisms/TicketBox/index.tsx
  client/src/hooks/meta/accountReducer/index.ts
  client/src/pages/BasedTemplate/templates/index.stories.tsx
  client/src/pages/BasedTemplate/templates/index.tsx
  client/src/pages/EventDetail/store.tsx
  client/src/pages/EventDetail/template/index.tsx
  client/src/pages/EventDetail/view.tsx
  client/src/pages/EventJoin/template/index.tsx
  client/src/pages/EventJoin/view.tsx
  client/src/pages/Login/index.tsx
  client/src/pages/Main/index.tsx
  client/src/pages/Main/template/index.tsx
  client/src/pages/NotFound/index.tsx
  client/src/pages/SignUp/store.tsx
  client/src/pages/SignUp/view.tsx
  client/src/stores/accountStore.tsx
  client/src/types/States.ts
Labels: ✨ Feature, 🌕 Frontend

#254 [PR] SignUp 에서 패스워드 관련된 변수와 참조 제거
  client/src/commons/constants/string.ts
  client/src/components/organisms/SignUpForm/index.stories.tsx
Labels: 🌕 Frontend

#252 [PR] 티켓 구매시 오류 메세지를 정형화함.
  reserve-server/src/constants/index.ts
  reserve-server/src/routes/api/controllers/authUser.ts
  reserve-server/src/routes/api/controllers/checkTicket.ts
  reserve-server/src/routes/api/controllers/orderTicket.ts
  reserve-server/src/services/transactions.ts
  reserve-server/test/api.spec.ts
Labels: 🌑 Backend, 🕊 API

#260 [PR] useStateReducer 디렉터리 이름 수정
  client/src/hooks/base/useStateReducer/index.ts
  client/src/pages/EventDetail/store.tsx
  client/src/pages/SignUp/store.tsx
Labels: 🌕 Frontend

#255 [PR] Client의 비동기 API 사용 개선
  client/src/apis/auth.ts
  client/src/apis/event.ts
  client/src/apis/index.ts
  client/src/apis/user.ts
  client/src/libs/axios.ts
  client/src/pages/EventJoin/view.tsx
  client/src/pages/Main/index.tsx
  client/src/pages/SignUp/store.tsx
  client/src/stores/accountStore.tsx
Labels: 🌕 Frontend

#213 [PR] 이벤트 글로벌 스토어
  client/package.json
  client/src/components/molecules/Card/index.spec.tsx
  client/src/components/molecules/Card/index.tsx
  client/src/components/organisms/CardGrid/index.stories.tsx
  client/src/components/organisms/CardGrid/index.tsx
  client/src/components/organisms/EventHeader/index.stories.tsx
  client/src/components/organisms/Ticket/__snapshots__/indes.spec.tsx.snap
  client/src/components/organisms/Ticket/indes.spec.tsx
  client/src/components/organisms/Ticket/index.stories.tsx
  client/src/components/organisms/TicketBox/index.stories.tsx
  client/src/hooks/index.ts
  client/src/hooks/meta/eventsReducer/index.ts
  client/src/pages/EventDetail/store.tsx
  client/src/pages/EventDetail/view.tsx
  client/src/pages/EventJoin/view.tsx
  client/src/pages/Main/index.tsx
  client/src/stores/eventsStore.tsx
  client/src/stores/index.tsx
  client/src/types/Actions.ts
  client/src/types/CustomHooks.ts
  client/src/types/Data.ts
  client/src/types/Event.ts
  client/src/types/States.ts
  client/src/utils/delay/index.ts
  yarn.lock
Labels: 🌕 Frontend

#249 [PR] 회원가입이 어떤 경우에던 가능하던 버그를 수정
  client/src/apis/user.ts
  client/src/pages/SignUp/store.tsx
  client/src/stores/accountStore.tsx
  server/src/routes/api/users/controllers/createUser.ts
  server/src/routes/api/users/index.ts
  server/src/routes/api/users/validators/createUser.ts
  server/src/routes/api/users/validators/index.ts
  server/src/services/users.ts
  server/src/utils/validateSignUpForms.ts
  server/test/utils/validateSignUpForms.spec.ts
Labels: 🌑 Backend, 🌕 Frontend, 🐛 BUG, 🕊 API

#266 [PR] 서버 모듈 절대 경로로 접근
  .travis.yml
  reserve-server/bin/www.ts
  reserve-server/nodemon.json
  reserve-server/package.json
  reserve-server/src/app.ts
  reserve-server/src/common/constants/index.ts
  reserve-server/src/routes/api/controllers/authUser.ts
  reserve-server/src/routes/api/controllers/checkTicket.ts
  reserve-server/src/routes/api/controllers/orderTicket.ts
  reserve-server/src/services/ticketCache.ts
  reserve-server/src/services/ticketType.ts
  reserve-server/src/services/transactions.ts
  reserve-server/src/services/userTicket.ts
  reserve-server/test/api.spec.ts
  reserve-server/tsc.args
  reserve-server/tsconfig.json
  server/bin/migrate.ts
  server/bin/redis-delete.ts
  server/bin/redis-migrate.ts
  server/bin/seed.ts
  server/bin/www.ts
  server/nodemon.json
  server/package.json
  server/src/app.ts
  server/src/routes/api/auth/controllers/authToken.ts
  server/src/routes/api/events/controllers/convertPlaceToCoordinate.ts
  server/src/routes/api/events/controllers/getEvents.ts
  server/src/routes/api/events/index.ts
  server/src/routes/api/events/middlewares/requestParamHandler.ts
  server/src/routes/api/users/controllers/createUser.ts
  server/src/routes/api/users/controllers/getUser.ts
  server/src/services/events.ts
  server/src/services/users.ts
  server/src/utils/redis.ts
  server/src/utils/sequelize.ts
  server/tsconfig.json
  yarn.lock
Labels: 🌑 Backend, 👷‍♀️ Enviornment

#268 [PR] 트라비스에서 describe, it 등 타입을 못찾던 warning 문제 해결
  .travis.yml
  server/test/api/event.spec.ts
  server/tsconfig.json
Labels: 🌑 Backend, 🏃‍♂️Test, 👷‍♀️ Enviornment

#261 [PR, 1MD/1MD] JoinEventPage(이벤트 예약) 고도화
  client/cypress/integration/eventjoin.spec.ts
  client/src/assets/img/check.svg
  client/src/commons/constants/number.ts
  client/src/commons/constants/string.ts
  client/src/components/atoms/ChkBox/__snapshots__/index.spec.tsx.snap
  client/src/components/atoms/ChkBox/index.spec.tsx
  client/src/components/atoms/ChkBox/index.stories.tsx
  client/src/components/atoms/ChkBox/index.tsx
  client/src/components/atoms/ChkBox/style.ts
  client/src/components/atoms/Divider/__snapshots__/index.spec.tsx.snap
  client/src/components/atoms/Divider/index.tsx
  client/src/components/atoms/GoogleMap/index.tsx
  client/src/components/atoms/GoogleMap/style.ts
  client/src/components/index.ts
  client/src/components/molecules/Counter/index.stories.tsx
  client/src/components/molecules/Counter/index.tsx
  client/src/components/molecules/Counter/style.ts
  client/src/components/molecules/StepList/__snapshots__/index.spec.tsx.snap
  client/src/components/molecules/StepList/index.spec.tsx
  client/src/components/molecules/StepList/index.stories.tsx
  client/src/components/molecules/StepList/index.tsx
  client/src/components/molecules/StepList/style.ts
  client/src/components/organisms/CounterBox/index.stories.tsx
  client/src/components/organisms/CounterBox/index.tsx
  client/src/components/organisms/CounterBox/style.ts
  client/src/components/organisms/EventSection/index.stories.tsx
  client/src/components/organisms/EventSection/index.tsx
  client/src/components/organisms/EventSection/style.ts
  client/src/components/organisms/Place/index.tsx
  client/src/components/organisms/Ticket/__snapshots__/indes.spec.tsx.snap
  client/src/components/organisms/Ticket/index.stories.tsx
  client/src/components/organisms/Ticket/index.tsx
  client/src/components/organisms/TicketBox/index.stories.tsx
  client/src/components/organisms/TicketBox/index.tsx
  client/src/components/organisms/TicketBox/style.ts
  client/src/pages/BasedTemplate/templates/index.tsx
  client/src/pages/EventDetail/template/index.tsx
  client/src/pages/EventJoin/index.tsx
  client/src/pages/EventJoin/store.tsx
  client/src/pages/EventJoin/style.ts
  client/src/pages/EventJoin/template/TicketChoice/index.tsx
  client/src/pages/EventJoin/template/TicketChoice/style.ts
  client/src/pages/EventJoin/template/TicketPurchase/index.tsx
  client/src/pages/EventJoin/template/TicketPurchase/style.ts
  client/src/pages/EventJoin/template/index.tsx
  client/src/pages/EventJoin/template/style.ts
  client/src/pages/EventJoin/view.tsx
Labels: ✨ Feature, 🌕 Frontend, 😏 Page

#290 [PR] tsconfig typeRoots 수정
  package.json
  reserve-server/package.json
  reserve-server/tsconfig.json
  server/package.json
  server/tsconfig.json
Labels: 🌑 Backend, 🐛 BUG, 👷‍♀️ Enviornment, 🚨 ASAP

#292 [PR] 서버 ts-node 실행 문제 fix
  reserve-server/tsconfig.json
  server/tsconfig.json
Labels: 🌑 Backend, 🐛 BUG

#267 [PR] 이벤트 글로벌 스토어, 디테일 페이지 적용
  client/src/apis/event.ts
  client/src/apis/index.ts
  client/src/components/atoms/ChkBox/__snapshots__/index.spec.tsx.snap
  client/src/components/atoms/GoogleMap/index.tsx
  client/src/components/atoms/Loading/index.stories.tsx
  client/src/components/atoms/Loading/index.tsx
  client/src/components/atoms/Loading/style.ts
  client/src/components/index.ts
  client/src/components/molecules/Card/index.tsx
  client/src/components/molecules/Card/style.ts
  client/src/components/organisms/CardGrid/index.stories.tsx
  client/src/components/organisms/CardGrid/index.tsx
  client/src/components/organisms/EventHeader/index.tsx
  client/src/components/organisms/Ticket/__snapshots__/indes.spec.tsx.snap
  client/src/hooks/base/useFetch/index.spec.tsx
  client/src/hooks/base/useFetch/index.ts
  client/src/hooks/meta/eventsReducer/index.ts
  client/src/pages/BasedTemplate/templates/index.tsx
  client/src/pages/BasedTemplate/templates/style.ts
  client/src/pages/EventDetail/index.stories.tsx
  client/src/pages/EventDetail/index.tsx
  client/src/pages/EventDetail/store.tsx
  client/src/pages/EventDetail/template/index.tsx
  client/src/pages/EventDetail/view.tsx
  client/src/pages/Main/index.tsx
  client/src/stores/eventsStore.tsx
  client/src/types/States.ts
Labels: 🌕 Frontend

#295 [PR] GET /api/users/tickets 마이페이지 내 티켓 확인용 API
  server/src/routes/api/users/controllers/getUserTickets.ts
  server/src/routes/api/users/controllers/index.ts
  server/src/routes/api/users/index.ts
  server/src/routes/api/users/validators/createUser.ts
  server/src/routes/middlewares/isLogin.ts
  server/src/services/index.ts
  server/src/services/userTickets.ts
  server/src/types/express/index.d.ts
  server/test/api/__snapshots__/user.spec.ts.snap
  server/test/api/user.spec.ts
Labels: 🌑 Backend, 🕊 API

#301 [PR] TUI Editor/Viewer 구현 및 적용
  client/package.json
  client/src/components/atoms/TuiEditor/index.stories.tsx
  client/src/components/atoms/TuiEditor/index.tsx
  client/src/components/atoms/TuiViewer/index.stories.tsx
  client/src/components/atoms/TuiViewer/index.tsx
  client/src/components/index.ts
  client/src/components/organisms/EventHeader/style.ts
  client/src/pages/EventDetail/index.tsx
  client/src/pages/EventDetail/template/index.tsx
  client/src/pages/EventDetail/template/style.ts
  yarn.lock
Labels: 🌕 Frontend, 🧩 Component

#298 [PR] DELETE /api/users/ticket 티켓 환불 API
  server/src/routes/api/users/controllers/deleteUserTicket.ts
  server/src/routes/api/users/controllers/getUserTickets.ts
  server/src/routes/api/users/controllers/index.ts
  server/src/routes/api/users/index.ts
  server/src/routes/api/users/validators/deleteUserTicket.ts
  server/src/routes/api/users/validators/index.ts
  server/src/services/index.ts
  server/src/services/userTickets.ts
  server/test/api/user.spec.ts
Labels: 🌑 Backend, 👶🏼참 잘했어요., 🕊 API

#304 [PR] 로그인 미들웨어 수정
  server/src/routes/api/users/controllers/getUserTickets.ts
  server/src/routes/api/users/index.ts
  server/src/routes/middlewares/index.ts
  server/src/routes/middlewares/requireLogin.ts
  server/src/utils/redis.ts
  server/test/middleware/requireLogin.spec.ts
Labels: 🌑 Backend, 🐛 BUG, 🕊 API

#309 [PR] Front-end에서 모든 스냅샷테스팅 제거
  client/package.json
  client/src/components/atoms/Btn/__snapshots__/index.spec.tsx.snap
  client/src/components/atoms/Btn/index.spec.tsx
  client/src/components/atoms/ChkBox/__snapshots__/index.spec.tsx.snap
  client/src/components/atoms/ChkBox/index.spec.tsx
  client/src/components/atoms/Divider/__snapshots__/index.spec.tsx.snap
  client/src/components/atoms/Divider/index.spec.tsx
  client/src/components/atoms/EventDate/__snapshots__/indes.spec.tsx.snap
  client/src/components/atoms/EventDate/indes.spec.tsx
  client/src/components/atoms/Icon/__snapshots__/index.spec.tsx.snap
  client/src/components/atoms/Icon/index.spec.tsx
  client/src/components/atoms/Img/__snapshots__/index.spec.tsx.snap
  client/src/components/atoms/Img/index.spec.tsx
  client/src/components/atoms/Input/__snapshots__/index.spec.tsx.snap
  client/src/components/atoms/Input/index.spec.tsx
  client/src/components/atoms/Label/__snapshots__/index.spec.tsx.snap
  client/src/components/atoms/Label/index.spec.tsx
  client/src/components/atoms/Price/__snapshots__/index.spec.tsx.snap
  client/src/components/atoms/Price/index.spec.tsx
  client/src/components/molecules/IconBtn/__snapshots__/index.spec.tsx.snap
  client/src/components/molecules/IconBtn/index.spec.tsx
  client/src/components/molecules/IconLabel/__snapshots__/index.spec.tsx.snap
  client/src/components/molecules/IconLabel/index.spec.tsx
  client/src/components/molecules/ImgBtn/__snapshots__/index.spec.tsx.snap
  client/src/components/molecules/ImgBtn/index.spec.tsx
  client/src/components/molecules/StepList/__snapshots__/index.spec.tsx.snap
  client/src/components/molecules/StepList/index.spec.tsx
  client/src/components/organisms/Ticket/__snapshots__/indes.spec.tsx.snap
  client/src/components/organisms/Ticket/indes.spec.tsx
Labels: 🌕 Frontend, 🏃‍♂️Test

#315 [PR] 메인페이지 추가 테스트
  client/cypress/integration/main.spec.ts
  client/src/App.tsx
  client/src/commons/style/animations/index.ts
  client/src/components/atoms/TuiEditor/index.stories.tsx
  client/src/components/atoms/TuiEditor/index.tsx
  client/src/components/molecules/FormItem/index.stories.tsx
  client/src/components/molecules/FormItem/index.tsx
  client/src/components/molecules/FormItem/style.ts
  client/src/components/organisms/MainBanner/index.tsx
  client/src/pages/EventCreate/index.tsx
  client/src/pages/EventJoin/index.tsx
  client/src/pages/EventJoin/style.ts
Labels: 🌕 Frontend, 🏃‍♂️Test, 😏 Page

#312 [PR] remove unused import and files
  client/src/pages/EventJoin/index.tsx
  client/src/pages/EventJoin/style.ts
Labels: 🌕 Frontend, 🐛 BUG, 🚨 ASAP

#316 [PR] Img Atom 스토리북 수정
  client/src/components/atoms/Img/index.stories.tsx
Labels: 🌕 Frontend, 🐛 BUG, 🧩 Component

#310 [PR] 유저가 주최한 이벤트 불러오기
  server/src/routes/api/users/controllers/getUserEvents.ts
  server/src/routes/api/users/controllers/index.ts
  server/src/routes/api/users/index.ts
  server/src/services/events.ts
  server/src/services/index.ts
  server/test/api/__snapshots__/user.spec.ts.snap
  server/test/api/user.spec.ts
Labels: 🌑 Backend, 🏃‍♂️Test, 🕊 API

#320 [PR] Storybook global knob in SignUp story 제거
  client/src/components/organisms/SignUpForm/index.stories.tsx
Labels: 🌕 Frontend, 🐛 BUG

#319 [Re-PR] react-icons 도입 및 svg 사용 수정
  client/package.json
  client/src/components/atoms/ChkBox/index.tsx
  client/src/components/atoms/GoogleMap/index.tsx
  client/src/components/atoms/Icon/index.stories.tsx
  client/src/components/molecules/Counter/index.tsx
  client/src/components/molecules/IconBtn/index.stories.tsx
  client/src/components/molecules/IconBtn/index.tsx
  client/src/components/molecules/IconBtn/style.ts
  client/src/components/molecules/IconLabel/index.stories.tsx
  client/src/components/molecules/IconLabel/index.tsx
  client/src/components/organisms/EventHeader/index.tsx
  client/src/components/organisms/Ticket/index.tsx
  client/src/components/organisms/TicketBox/index.tsx
  client/src/pages/Login/index.tsx
  client/src/pages/Login/templates/index.tsx
  client/src/pages/Login/templates/style.ts
  yarn.lock
Labels: 🌕 Frontend

#317 [PR] GET /api/events/:eventId/users 이벤트의 참여자들의 리스트를 불러오는 API
  server/src/routes/api/events/controllers/getAttendants.ts
  server/src/routes/api/events/controllers/index.ts
  server/src/routes/api/events/index.ts
  server/src/services/index.ts
  server/src/services/userTickets.ts
  server/test/api/__snapshots__/event.spec.ts.snap
  server/test/api/event.spec.ts
Labels: 🌑 Backend, 👶🏼참 잘했어요., 🕊 API

#325 [PR] PATCH /api/events/:eventId/ticket/:ticketId 티켓 출석 체크 토글링 API
  server/db_seeds/userTickets.json
  server/src/routes/api/events/controllers/checkAttendance.ts
  server/src/routes/api/events/controllers/index.ts
  server/src/routes/api/events/index.ts
  server/src/routes/api/events/validators/checkAttendance.ts
  server/src/routes/api/events/validators/index.ts
  server/src/services/index.ts
  server/src/services/userTickets.ts
  server/test/api/event.spec.ts
  server/test/db/__snapshots__/seed.spec.ts.snap
Labels: 🌑 Backend, 🕊 API

#324 [PR] CardGrid를 범용적으로 개선
  client/src/commons/constants/number.ts
  client/src/components/organisms/CardGrid/index.stories.tsx
  client/src/components/organisms/CardGrid/index.tsx
  client/src/pages/Main/index.tsx
Labels: 🌕 Frontend, 🧩 Component

#329 [PR] 리드미 이미지 업데이트
  README.md
Labels: 📒 Document

#327 [PR] 티켓 삭제시에 트렌젝션을 통해 leftCnt 를 늘리고, redis Block 을 풀어줌.
  server/src/routes/api/users/controllers/deleteUserTicket.ts
  server/src/services/userTickets.ts
  server/src/utils/redis.ts
  server/test/api/event.spec.ts
  server/test/api/user.spec.ts
Labels: 🌑 Backend, 🕊 API

#291 [PR] MyPage(마이페이지) 작성
  client/package.json
  client/src/App.tsx
  client/src/apis/auth.ts
  client/src/apis/event.ts
  client/src/apis/index.ts
  client/src/apis/user.ts
  client/src/commons/constants/routes.ts
  client/src/commons/constants/string.ts
  client/src/components/atoms/EventDate/index.tsx
  client/src/components/atoms/LNBItem/index.stories.tsx
  client/src/components/atoms/LNBItem/index.tsx
  client/src/components/atoms/LNBItem/style.ts
  client/src/components/atoms/Price/index.stories.tsx
  client/src/components/atoms/Price/index.tsx
  client/src/components/index.ts
  client/src/components/molecules/Card/index.tsx
  client/src/components/molecules/Card/style.ts
  client/src/components/molecules/LNB/index.stories.tsx
  client/src/components/molecules/LNB/index.tsx
  client/src/components/molecules/LNB/style.ts
  client/src/components/organisms/CardGrid/index.stories.tsx
  client/src/components/organisms/CardGrid/index.tsx
  client/src/components/organisms/EventHeader/index.tsx
  client/src/components/organisms/EventSection/index.stories.tsx
  client/src/components/organisms/EventSection/style.ts
  client/src/components/organisms/Header/index.tsx
  client/src/components/organisms/Ticket/index.tsx
  client/src/components/organisms/TicketBox/index.stories.tsx
  client/src/components/organisms/TicketBox/index.tsx
  client/src/components/organisms/TicketBox/style.ts
  client/src/hooks/base/useApiRequest/index.ts
  client/src/pages/EventJoin/index.tsx
  client/src/pages/Main/index.tsx
  client/src/pages/MyPage/index.stories.tsx
  client/src/pages/MyPage/index.tsx
  client/src/pages/MyPage/reducer.ts
  client/src/pages/MyPage/template/BoughtTicketEvent/index.tsx
  client/src/pages/MyPage/template/BoughtTicketEvent/style.ts
  client/src/pages/MyPage/template/CreatedEvents/index.tsx
  client/src/pages/MyPage/template/CreatedEvents/style.ts
  client/src/pages/MyPage/template/Tickets/index.tsx
  client/src/pages/MyPage/template/Tickets/style.ts
  client/src/pages/MyPage/template/index.tsx
  client/src/pages/MyPage/template/style.ts
  client/src/pages/SignUp/store.tsx
  client/src/pages/index.ts
  client/src/stores/accountStore.tsx
  client/src/stores/eventsStore.tsx
  client/src/types/Actions.ts
  client/src/types/Data.ts
  client/src/types/States.ts
  client/src/utils/dateCalculator/index.ts
  yarn.lock
Labels: 🌕 Frontend, 😏 Page

#337 [PR] 이벤트 참여 페이지에서 이벤트 내용이 정상적으로 보여지지 않는 현상 해결
  client/src/components/organisms/Place/index.stories.tsx
  client/src/components/organisms/Place/index.tsx
  client/src/hooks/base/useApiRequest/index.ts
  client/src/pages/EventDetail/index.tsx
  client/src/pages/EventJoin/index.tsx
  client/src/types/Data.ts
Labels: 🌕 Frontend, 🐛 BUG

#361 [PR] DB seed를 제외한 테스트 스크립트 작성
  server/package.json
Labels: 🌑 Backend

#376 [PR] Refactor 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/refactor.md
Labels: 📒 Document

#375 [PR] W6 리뷰에 따른 리팩토링
  client/src/apis/auth.ts
  client/src/apis/event.ts
  client/src/apis/user.ts
  client/src/components/molecules/LNB/index.tsx
  client/src/components/molecules/StepList/index.tsx
  client/src/components/organisms/CardGrid/index.stories.tsx
  client/src/components/organisms/TicketBox/index.tsx
  client/src/hooks/base/useApiRequest/index.ts
  client/src/hooks/meta/accountReducer/index.ts
  client/src/pages/EventJoin/index.tsx
  client/src/pages/MyPage/index.tsx
  client/src/pages/MyPage/reducer.ts
  client/src/pages/SignUp/store.tsx
  client/src/stores/accountStore.tsx
  client/src/stores/eventsStore.tsx
Labels: 🌕 Frontend, 👨🏻‍⚕️Refactor

#372 [PR] Cypress, Test 관련 내용 추가
  README.md
Labels: 📒 Document

#371 [PR] Cypress video recording 추가
  .travis.yml
  client/cypress.json
  client/package.json
Labels: 🌕 Frontend, 🏃‍♂️Test

#366 [PR] TicketBox에서 종료일자 계산 개선
  client/src/components/organisms/TicketBox/index.tsx
  client/src/utils/dateCalculator/index.spec.ts
Labels: 🌕 Frontend, 👨🏻‍⚕️Refactor

#362 [PR] 성과 이름의 vaildation 이 다르게 보여지는 문제 해결
  client/cypress/integration/signup.spec.ts
  client/src/commons/constants/string.ts
  client/src/pages/SignUp/view.tsx
Labels: 🌕 Frontend, 🔧 FIX

#364 [PR] EventDetail(이벤트 상세 페이지) 에서 date format 미설정
  client/src/components/atoms/EventDate/index.tsx
  client/src/components/organisms/EventHeader/index.tsx
  client/src/components/organisms/EventHeader/style.ts
Labels: 🌕 Frontend, 🔧 FIX

#302 [PR] ImageSelector component
  client/src/commons/constants/string.ts
  client/src/components/atoms/ImgSelector/index.stories.tsx
  client/src/components/atoms/ImgSelector/index.tsx
  client/src/components/atoms/ImgSelector/style.ts
  client/src/components/index.ts
Labels: 🌑 Backend, 🧩 Component

#370 [PR] 트라비스에서 시드 테스트 먼저 진행 후 다른 테스트 진행
  .travis.yml
Labels: 🌑 Backend, 🏃‍♂️Test, 👷‍♀️ Enviornment, 📚 Database

#382 [PR] travis s3 key 제거 및 cypress record key 추가
  .travis.yml
Labels: 🌈 DevOps, 👷‍♀️ Enviornment

#380 [PR] 위도 경도를 찾는 API 제거
  server/.env.template
  server/src/routes/api/events/controllers/convertPlaceToCoordinate.ts
  server/src/routes/api/events/controllers/index.ts
  server/src/routes/api/events/index.ts
  server/test/api/event.spec.ts
Labels: 🌑 Backend, 👨🏻‍⚕️Refactor

#392 [PR] Disable Cypress video recording
  client/package.json
Labels: 🌕 Frontend, 🏃‍♂️Test

#388 [PR] param 검증
  server/src/routes/api/events/index.ts
  server/src/routes/api/users/index.ts
  server/src/routes/middlewares/index.ts
  server/src/routes/middlewares/paramsValidator.ts
  server/test/middleware/paramsValidator.spec.ts
Labels: 🌑 Backend, 👨🏻‍⚕️Refactor

#396 [PR] 서비스 함수들을 파일 단위로 분리하기
  server/src/routes/api/events/controllers/checkAttendance.ts
  server/src/routes/api/events/controllers/getAttendants.ts
  server/src/routes/api/users/controllers/deleteUserTicket.ts
  server/src/routes/api/users/controllers/getUserEvents.ts
  server/src/routes/api/users/controllers/getUserTickets.ts
  server/src/routes/api/users/validators/createUser.ts
  server/src/services/events.ts
  server/src/services/events/createEventAndTicket.ts
  server/src/services/events/getEventById.ts
  server/src/services/events/getEvents.ts
  server/src/services/events/getUserEventsByUserId.ts
  server/src/services/events/index.ts
  server/src/services/index.ts
  server/src/services/userTickets.ts
  server/src/services/userTickets/deleteUserTicketById.ts
  server/src/services/userTickets/getUserTicketsByTicketId.ts
  server/src/services/userTickets/getUserTicketsByUserId.ts
  server/src/services/userTickets/index.ts
  server/src/services/userTickets/toggleUserAttendance.ts
  server/src/services/users.ts
  server/src/services/users/getUserByGoogleId.ts
  server/src/services/users/getUserById.ts
  server/src/services/users/index.ts
  server/src/services/users/setUser.ts
  server/src/services/users/setUserInfo.ts
  server/src/utils/passport.ts
Labels: 🌑 Backend, 👨🏻‍⚕️Refactor

#330 [PR] 지도 검색 컴포넌트 구현
  client/.env.template
  client/.storybook/preview-head.html
  client/public/index.html
  client/src/apis/index.ts
  client/src/apis/map.ts
  client/src/components/atoms/GoogleMap/index.tsx
  client/src/components/atoms/Input/index.tsx
  client/src/components/atoms/KakaoMap/index.stories.tsx
  client/src/components/atoms/KakaoMap/index.tsx
  client/src/components/atoms/KakaoMap/style.ts
  client/src/components/atoms/TuiEditor/index.tsx
  client/src/components/atoms/TuiViewer/index.tsx
  client/src/components/index.ts
  client/src/components/molecules/DropDown/index.stories.tsx
  client/src/components/molecules/DropDown/index.tsx
  client/src/components/molecules/DropDown/style.ts
  client/src/components/molecules/SearchMap/index.stories.tsx
  client/src/components/molecules/SearchMap/index.tsx
  client/src/components/molecules/SearchMap/style.tsx
  client/src/components/organisms/Place/index.tsx
  client/src/hooks/base/useDebounce/index.ts
  client/src/hooks/index.ts
  client/src/pages/BasedTemplate/templates/style.ts
  client/src/pages/EventJoin/index.tsx
Labels: 🌕 Frontend, 🧩 Component

#408 [PR] currencyDecorator 일반화 및 InputOnlyNumber 컴포넌트 구현
  client/src/components/atoms/InputOnlyNumber/index.stories.tsx
  client/src/components/atoms/InputOnlyNumber/index.tsx
  client/src/components/atoms/Price/index.tsx
  client/src/utils/numberDecorator/index.spec.ts
  client/src/utils/numberDecorator/index.ts
Labels: 🌕 Frontend, 🧩 Component

#404 [PR] 클라이언트 리사이징된 이미지로 요청하기
  client/.env.template
  client/src/pages/EventDetail/index.tsx
  client/src/pages/Main/index.tsx
  client/src/utils/getImageURL/imageTypes.ts
  client/src/utils/getImageURL/index.ts
Labels: 🌕 Frontend, 👨🏻‍⚕️ Refactor

#395 [PR] 로그아웃시 쿠키가 현재 존재하는지 검사하는 로직 & Private Router 만듦
  .gitignore
  client/.env.template
  client/cypress.json
  client/cypress/integration/eventjoin.spec.ts
  client/cypress/integration/header.spec.ts
  client/cypress/integration/main.spec.ts
  client/src/App.tsx
  client/src/components/atoms/EventDate/index.tsx
  client/src/components/atoms/EventDate/style.ts
  client/src/stores/accountStore.tsx
  server/src/routes/api/auth/controllers/authToken.ts
Labels: 🌑 Backend, 🌕 Frontend, 🕊 API

#403 [PR] event seed main image 에서 url 제거
  server/db_seeds/events.json
  server/src/routes/api/events/controllers/createEvent.ts
  server/test/api/__snapshots__/user.spec.ts.snap
  server/test/db/__snapshots__/seed.spec.ts.snap
Labels: 🌑 Backend, 👷‍♀️ Enviornment, 📚 Database

#378 [PR] Front-end에서 상태관리(비동기 처리)와 디렉터리 재구성
  client/src/commons/constants/string.ts
  client/src/hooks/base/useStateReducer/index.ts
  client/src/hooks/index.ts
  client/src/hooks/useApiRequest.ts
  client/src/hooks/useDebounce.ts
  client/src/hooks/useFetch.spec.tsx
  client/src/hooks/useFetch.ts
  client/src/hooks/useIntersect.ts
  client/src/pages/MyPage/actions.ts
  client/src/pages/MyPage/index.tsx
  client/src/pages/MyPage/reducer.ts
  client/src/pages/MyPage/store.tsx
  client/src/pages/MyPage/template/index.tsx
  client/src/pages/MyPage/view.tsx
  client/src/pages/SignUp/store.tsx
  client/src/stores/accountStore/index.tsx
  client/src/stores/accountStore/reducer.ts
  client/src/stores/afterLoginStore/index.tsx
  client/src/stores/eventsStore/index.tsx
  client/src/stores/eventsStore/reducer.ts
  client/src/types/Actions.ts
  client/src/types/CustomHooks.ts
  client/src/types/States.ts
Labels: 🌕 Frontend, 👨🏻‍⚕️ Refactor

#399 [PR] 환경변수 로딩 개선
  .travis.yml
  server/bin/www.ts
  server/src/env.ts
Labels: 🌑 Backend, 👨🏻‍⚕️ Refactor, 👷‍♀️ Enviornment

#397 [PR] html lang을 ko로 변경함
  client/public/index.html
Labels: 🌕 Frontend

#414 [PR] 무료 이벤트에 대해 표시되는 텍스트 수정
  client/src/components/atoms/Price/index.tsx
Labels: 🌕 Frontend, 👨🏻‍⚕️ Refactor

#419 [PR] Private Router 개선
  client/src/App.tsx
Labels: 🌕 Frontend, 👨🏻‍⚕️ Refactor

#411 [PR] 백엔드 테스트 코드 리팩토링
  server/src/utils/readJSON.ts
  server/test/api/__snapshots__/user.spec.ts.snap
  server/test/api/event.spec.ts
  server/test/api/user.spec.ts
  server/test/db/seed.spec.ts
  server/test/middleware/requireLogin.spec.ts
  server/test/utils/__snapshots__/readJSON.spec.ts.snap
  server/test/utils/file/test.json
  server/test/utils/readJSON.spec.ts
  server/test/utils/validateSignUpForms.spec.ts
Labels: 🌑 Backend, 🏃‍♂️Test, 👨🏻‍⚕️ Refactor

#422 [PR] useApiRequest 성공 / 에러 핸들링 개선
  client/src/hooks/useApiRequest.ts
Labels: 🌕 Frontend

#416 [PR] DatePicker 및 날짜 유효성 검사
  client/package.json
  client/src/commons/constants/string.ts
  client/src/components/atoms/Input/index.tsx
  client/src/components/atoms/InputOnlyNumber/index.tsx
  client/src/components/atoms/TimePicker/index.stories.tsx
  client/src/components/atoms/TimePicker/index.tsx
  client/src/components/atoms/TimePicker/style.ts
  client/src/components/index.ts
  client/src/components/molecules/DateTimePicker/index.stories.tsx
  client/src/components/molecules/DateTimePicker/index.tsx
  client/src/components/molecules/DateTimePicker/style.ts
  yarn.lock
Labels: 🌕 Frontend, 🧩 Component

#415 [PR] 마이페이지 - 등록한 페이지
  client/src/apis/index.ts
  client/src/apis/user.ts
  client/src/commons/constants/number.ts
  client/src/commons/constants/string.ts
  client/src/components/organisms/EventSection/index.tsx
  client/src/components/organisms/EventSection/style.ts
  client/src/components/organisms/TicketBox/index.tsx
  client/src/components/organisms/TicketBox/style.ts
  client/src/pages/MyPage/helper.tsx
  client/src/pages/MyPage/template/BoughtTicketEvent/index.tsx
  client/src/pages/MyPage/template/BoughtTicketEvent/style.ts
  client/src/pages/MyPage/template/index.tsx
  client/src/pages/MyPage/view.tsx
  client/src/types/Data.ts
Labels: ✨ Feature, 🌕 Frontend, 😏 Page

#431 [PR] 이벤트 만들기 API 검증 로직 수정
  client/cypress/integration/eventjoin.spec.ts
  server/src/routes/api/events/validators/createEvent.ts
  server/test/api/event.spec.ts
Labels: 🌑 Backend, 🐛 BUG, 🔧 FIX

#434 [PR] 이벤트 티켓 구매 페이지에서 이미지 안나오는 문제 해결
  client/src/pages/EventJoin/index.tsx
  client/src/utils/getImageURL/imageTypes.ts
Labels: 🌕 Frontend, 🐛 BUG, 🔧 FIX

#436 [1차 / PR] 셀프-버그데이 / 티켓 구매, 상세, 마이페이지 트러블슈팅
  client/src/components/molecules/LNB/index.tsx
  client/src/hooks/useApiRequest.ts
  client/src/pages/MyPage/helper.tsx
  client/src/pages/MyPage/template/BoughtTicketEvent/style.ts
  client/src/pages/MyPage/view.tsx
  client/src/utils/getImageURL/imageTypes.ts
Labels: 🌕 Frontend, 🔧 FIX

#439 [PR] 이벤트 만들기 검증 버그 수정
  server/src/routes/api/events/validators/createEvent.ts
Labels: 🌑 Backend, 🐛 BUG

#443 [PR] 이벤트 만들기 API 검증에서 설명을 optional 로 하기
  server/src/routes/api/events/validators/createEvent.ts
Labels: 🌑 Backend, 🐛 BUG

#445 [PR] Img Selector 에서 File Size Limit 기능 추가
  client/src/commons/constants/string.ts
  client/src/components/atoms/ImgSelector/index.stories.tsx
  client/src/components/atoms/ImgSelector/index.tsx
Labels: 🌕 Frontend, 🧩 Component

#440 [PR / 2차] 티켓 구매, 상세, 마이페이지 트러블슈팅
  client/src/apis/user.ts
  client/src/commons/constants/string.ts
  client/src/components/molecules/Counter/index.tsx
  client/src/components/molecules/IconBtn/index.stories.tsx
  client/src/components/molecules/IconBtn/index.tsx
  client/src/components/organisms/EventHeader/index.tsx
  client/src/components/organisms/EventHeader/style.ts
  client/src/hooks/useApiRequest.ts
  client/src/pages/Login/index.tsx
  client/src/pages/MyPage/actions.ts
  client/src/pages/MyPage/helper.tsx
  client/src/pages/MyPage/store.tsx
  client/src/pages/MyPage/view.tsx
  server/src/routes/api/users/controllers/deleteUserTicket.ts
  server/test/api/user.spec.ts
Labels: 🌕 Frontend, 👨🏻‍⚕️ Refactor, 🔧 FIX

#447 [PR / 3차] 티켓 구매, 상세, 마이페이지 트러블슈팅
  client/src/components/organisms/EventHeader/index.tsx
  client/src/components/organisms/Ticket/index.tsx
  client/src/components/organisms/Ticket/style.ts
  client/src/components/organisms/TicketBox/index.tsx
  client/src/pages/EventDetail/index.tsx
  client/src/pages/EventJoin/index.tsx
Labels: 🌕 Frontend, 🔧 FIX

#456 [PR] 티켓 남은 개수가 안보여야 할 경우, 티켓의 leftCnt 를 -1 로 변경해서 보내줌.
  server/src/services/events/getEventById.ts
  server/src/services/events/getEvents.ts
Labels: 🌑 Backend, 🔧 FIX, 🕊 API

#464 [PR] travis 빌드 fail 해결 및 재발 방지
  client/.eslintrc.json
  client/src/components/molecules/IconBtn/index.tsx
  client/src/components/organisms/Ticket/style.ts
  client/src/hooks/useFetch.spec.tsx
Labels: 🌕 Frontend, 👷‍♀️ Enviornment

#460 [PR] 티켓 가격 0원 허용
  client/src/pages/EventCreate/store.tsx
  server/src/routes/api/events/validators/createEvent.ts
Labels: 🌑 Backend, 🔧 FIX, 🕊 API

#465 [PR] 이벤트 상세, 예약페이지 개선
  client/cypress/integration/eventjoin.spec.ts
  client/src/commons/constants/string.ts
  client/src/components/organisms/EventHeader/index.tsx
  client/src/components/organisms/Ticket/index.tsx
  client/src/components/organisms/Ticket/style.ts
  client/src/pages/EventDetail/index.tsx
  client/src/pages/EventJoin/index.tsx
  client/src/pages/EventJoin/template/index.tsx
  client/src/pages/EventJoin/template/style.ts
Labels: 🌕 Frontend, 🔧 FIX

#475 [PR] 비공개이더라도 매진이면 left count를 0으로 보내기
  server/src/services/events/getEventById.ts
  server/src/services/events/getEvents.ts
Labels: 🌑 Backend, 🔧 FIX, 🕊 API

#474 [PR] 이벤트 디테일/조인 페이지에서 무조건 API 콜하기
  client/cypress/integration/eventjoin.spec.ts
  client/src/pages/EventDetail/index.tsx
  client/src/pages/EventJoin/index.tsx
  client/src/pages/EventJoin/template/index.tsx
Labels: 🌕 Frontend, 👨🏻‍⚕️ Refactor, 😏 Page

#471 [PR] warning, leftCnt, UTC Time 관련 개선
  client/src/commons/constants/string.ts
  client/src/components/organisms/EventHeader/index.tsx
  client/src/components/organisms/EventSection/index.tsx
  client/src/components/organisms/EventSection/style.ts
  client/src/components/organisms/Ticket/index.tsx
  client/src/components/organisms/Ticket/style.ts
  client/src/pages/EventDetail/index.tsx
  client/src/pages/EventJoin/index.tsx
  client/src/pages/MyPage/view.tsx
Labels: 🌕 Frontend, 🔧 FIX

#476 [PR] event join 을 체크하는 react router 생성, reserve server에서 관련 로직을 체킹
  client/src/App.tsx
  client/src/apis/event.ts
  client/src/apis/index.ts
  reserve-server/src/routes/api/controllers/checkTicket.ts
  reserve-server/src/routes/api/index.ts
Labels: 🌕 Frontend, 👨🏻‍⚕️ Refactor

#483 [PR] MyPage context를 state, action 으로 분리
  client/src/pages/MyPage/store.tsx
  client/src/pages/MyPage/view.tsx
Labels: 🌕 Frontend, 👨🏻‍⚕️ Refactor

#480 [PR] Travis에서 Cypress 알 수 없는 빌드 fail 해결
  client/cypress.json
  client/cypress/fixtures/reserve_event.json
  client/cypress/integration/eventjoin.spec.ts
  client/cypress/integration/header.spec.ts
  client/cypress/integration/main.spec.ts
  server/db_seeds/events.json
  server/db_seeds/ticketTypes.json
  server/test/db/__snapshots__/seed.spec.ts.snap
Labels: 🌕 Frontend, 🏃‍♂️Test

#492 [PR] 이벤트 만들기 API 리턴값 수정
  server/src/routes/api/events/controllers/createEvent.ts
Labels: 🌑 Backend, 🕊 API

#493 [PR] 이벤트 만들기 폼 시간 버그
  client/src/commons/constants/number.ts
  client/src/commons/constants/string.ts
  client/src/components/molecules/DateTimePicker/index.tsx
  client/src/pages/EventCreate/store.tsx
  client/src/pages/EventCreate/view.tsx
  client/src/stores/eventsStore/index.tsx
  client/src/stores/eventsStore/reducer.ts
  client/src/utils/validateInput/index.ts
Labels: 🌕 Frontend, 🔧 FIX

#495 [PR] 티켓 구입 타이머 버튼
  client/src/components/organisms/EventHeader/index.tsx
Labels: ✨ Feature, 🌕 Frontend

#496 [PR] Cypress에서의 스크롤 이벤트 wait를 낭낭하게 주었습니다.
  client/cypress/integration/main.spec.ts
Labels: 🌕 Frontend, 🔧 FIX

#505 [PR] Cypress 버전 업데이트 (3.6.3 => 3.8.0)
  client/package.json
  yarn.lock
Labels: 🌕 Frontend

#507 [PR] 이미지 셀렉터 파일 재선택시 취소 눌렀을 때 에러 처리
  client/src/components/atoms/ImgSelector/index.tsx
Labels: 🌕 Frontend, 🐛 BUG, 🔧 FIX, 🧩 Component

#515 [PR] 이벤트 만들 때, 날짜 입력을 키보드로 입력가능하게 함
  client/src/commons/constants/string.ts
  client/src/components/molecules/DateTimePicker/index.tsx
Labels: 🌕 Frontend, 🔧 FIX

#514 [PR] TUI editor 이미지 버튼 제거
  client/src/components/atoms/TuiEditor/index.tsx
Labels: 🌕 Frontend, 🔧 FIX, 🧩 Component

#506 [PR] 각 페이지에 대한 기존 Cypress 테스트 케이스 추가
  client/.eslintrc.json
  client/cypress.json
  client/cypress/fixtures/auth.json
  client/cypress/fixtures/events/always_buy_refund_event.json
  client/cypress/fixtures/events/bought_maximum_ticket_event.json
  client/cypress/fixtures/events/end_event.json
  client/cypress/fixtures/events/event.json
  client/cypress/fixtures/events/events.json
  client/cypress/fixtures/events/fetched_events.json
  client/cypress/fixtures/events/has_many_tickets_event.json
  client/cypress/fixtures/events/has_one_ticket_event.json
  client/cypress/fixtures/events/my_events.json
  client/cypress/fixtures/events/not_over_sale_event.json
  client/cypress/fixtures/events/over_refund_event.json
  client/cypress/fixtures/events/over_sale_event.json
  client/cypress/fixtures/events/sold_out_event.json
  client/cypress/fixtures/example.json
  client/cypress/fixtures/profile.json
  client/cypress/fixtures/tickets/my_ticket.json
  client/cypress/fixtures/users.json
  client/cypress/integration/eventdetail.spec.ts
  client/cypress/integration/eventjoin.spec.ts
  client/cypress/integration/header.spec.ts
  client/cypress/integration/login.spec.ts
  client/cypress/integration/main.spec.ts
  client/cypress/integration/mypage.spec.ts
  client/cypress/integration/signup.spec.ts
  client/cypress/support/commands.js
  client/cypress/support/commands.ts
  client/src/components/atoms/LNBItem/index.tsx
  client/src/components/molecules/IconLabel/index.tsx
  client/src/components/organisms/EventHeader/index.tsx
  client/src/components/organisms/EventSection/index.tsx
  client/src/components/organisms/EventSection/style.ts
  client/src/components/organisms/Ticket/index.tsx
  client/src/components/organisms/TicketBox/index.tsx
  client/src/pages/Login/index.tsx
  client/src/pages/Login/templates/index.tsx
  client/src/pages/Login/templates/style.ts
  server/db_seeds/events.json
  server/package.json
  server/test/api/__snapshots__/user.spec.ts.snap
  server/test/db/__snapshots__/seed.spec.ts.snap
  yarn.lock
Labels: 🌕 Frontend, 🏃‍♂️Test
