Repository connect-foundation/2019-12, pull requests merged in 2019-11, with the labels that each got.

#32 [PR] #8 프로젝트 템플릿
  server/package.json
  server/server.dev.compose.yml
  server/src/app.ts
  server/src/routes/api/users/controllers/createUser.ts
  server/src/routes/api/users/index.ts
  yarn.lock
Labels: DevOps, backend

#38 [PR] 공통 헤더 컴포넌트 작성
  .travis.yml
  client/src/commons/components/atoms/Logo/index.tsx
  client/src/commons/components/molecules/ExampleItem/index.tsx
  client/src/commons/components/organisms/ExampleContainer/index.tsx
  client/src/commons/constants/string.ts
  client/src/components/atoms/AccountBtn/index.tsx
  client/src/components/atoms/AccountBtn/style.ts
  client/src/components/atoms/CreateEventBtn/index.tsx
  client/src/components/atoms/CreateEventBtn/style.ts
  client/src/components/atoms/LogoBtn/index.tsx
  client/src/components/atoms/LogoBtn/style.ts
  client/src/components/molecules/HeaderContainer/index.tsx
  client/src/components/molecules/HeaderContainer/style.ts
  client/stories/0-atom/0-Text.stories.tsx
  client/stories/0-atom/1-Button.stories.tsx
  client/stories/1-molecules/0-Card.stories.tsx
  client/stories/1-molecules/0-Container.stories.tsx
  client/stories/2-organisms/0-Form.stories.tsx
  client/stories/3-Templates.stories.tsx
  client/stories/4-Pages.stories.tsx
  package.json
Labels: component, feature, frontend

#33 #5 [PR] 서버 Travis 환경 TS에 맞도록 재설정, server test template 재작성
  .travis.yml
  package.json
  server/package.json
  server/test/template.spec.ts
  server/tsconfig.json
  yarn.lock
Labels: DevOps, backend, test

#43 [PR]
  client/stories/0-atom/1-Button.stories.tsx
Labels: bug, frontend

#46 [TEMP_REVIEW] 리뷰용 피처 머지
  .travis.yml
  package.json
  server/package.json
  server/server.dev.compose.yml
  server/src/app.ts
  server/src/routes/api/users/controllers/createUser.ts
  server/src/routes/api/users/index.ts
  server/test/template.spec.ts
  server/tsconfig.json
  yarn.lock
Labels: review

#50 Hotfix 49 - 린트 툴 버그
  .commitlintrc.json
  .prettierignore
  client/.eslintrc.json
  client/.storybook/webpack.config.js
  client/cypress.json
  client/cypress/fixtures/example.json
  client/cypress/fixtures/profile.json
  client/cypress/fixtures/users.json
  client/cypress/plugins/index.js
  client/cypress/support/index.js
  client/jest.config.js
  client/package.json
  client/tsconfig.json
  package.json
  server/.eslintrc.json
  server/nodemon.json
  server/package.json
  server/tsconfig.json
  yarn.lock
Labels: bug

#57 [PR] Client 환경구성 및 문서화
  client/.storybook/addons.ts
  client/.storybook/config.ts
  client/.storybook/webpack.config.js
  client/package.json
  client/src/setupTests.ts
  client/tsconfig.json
  yarn.lock
Labels: document, feature, frontend

#58 [PR] 데이터베이스 모델링
  .commitlintrc.json
  .dockerignore
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/feature_component.md
  .github/ISSUE_TEMPLATE/feature_page.md
  .github/ISSUE_TEMPLATE/issue.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierignore
  client/.eslintrc.json
  client/.storybook/webpack.config.js
  client/cypress.json
  client/cypress/fixtures/example.json
  client/cypress/fixtures/profile.json
  client/cypress/fixtures/users.json
  client/cypress/plugins/index.js
  client/cypress/support/index.js
  client/package.json
  client/src/App.spec.tsx
  client/src/commons/components/atoms/Logo/index.tsx
  client/src/commons/components/molecules/ExampleItem/index.tsx
  client/src/commons/components/organisms/ExampleContainer/index.tsx
  client/stories/0-atom/0-Text.stories.tsx
  client/stories/1-molecules/0-Card.stories.tsx
  client/stories/2-organisms/0-Form.stories.tsx
  client/stories/3-Templates.stories.tsx
  client/stories/4-Pages.stories.tsx
  client/tsconfig.json
  package.json
  server/.env
  server/.eslintrc.json
  server/bin/www.ts
  server/nodemon.json
  server/package.json
  server/src/env.ts
  server/src/models/Event.ts
  server/src/models/Order.ts
  server/src/models/OrderTicket.ts
  server/src/models/TicketSubscription.ts
  server/src/models/TicketType.ts
  server/src/models/User.ts
  server/src/models/index.ts
  server/src/services/sequelize.ts
  server/test/template.spec.ts
  server/tsconfig.json
  yarn.lock
Labels: backend, feature

#69 [PR] React-router-dom 추가
  client/package.json
  client/src/App.css
  client/src/App.tsx
  yarn.lock
Labels: feature, frontend

#71 [Hotfix] typecheking on commit
  client/package.json
  package.json
  server/package.json
  server/tsc.args
  yarn.lock
Labels: backend, bug

#75 [PR] Travis 환경변수와 DB 설정
  .gitignore
  .travis.yml
  client/package.json
  package.json
  server/bin/migrate.ts
  server/bin/www.ts
  server/nodemon.json
  server/package.json
  server/src/app.ts
  server/src/config/oauth_google.ts
  server/src/config/server_url.ts
  server/src/routes/api/auth/index.ts
  server/src/routes/api/users/controllers/createUser.ts
  server/src/services/index.ts
  server/src/services/passport.ts
  server/test/db/model.spec.ts
  server/tsc.args
  yarn.lock
Labels: DevOps, backend, feature

#80 [PR] 모델 변경
  server/src/models/Event.ts
  server/src/models/Order.ts
  server/src/models/OrderTicket.ts
  server/src/models/TicketSubscription.ts
  server/src/models/TicketType.ts
  server/src/models/User.ts
Labels: backend, database

#79 [PR] Front-End 를 Travis에서 이미지화 한 뒤, hub에 올림.
  .gitignore
  .travis.yml
  client/Dockerfile
Labels: DevOps, frontend

#40 #17 [PR] LoginPage 제작
  .gitignore
  client/src/App.tsx
  client/src/assets/img/google.svg
  client/src/commons/constants/routes.ts
  client/src/commons/constants/string.ts
  client/src/components/atoms/Btn/index.stories.tsx
  client/src/components/atoms/Btn/index.tsx
  client/src/components/atoms/Btn/style.ts
  client/src/components/atoms/Icon/index.tsx
  client/src/components/molecules/IconBtn/index.tsx
  client/src/components/molecules/IconBtn/style.ts
  client/src/components/organisms/Footer/style.ts
  client/src/components/organisms/Header/index.stories.tsx
  client/src/components/organisms/Header/index.tsx
  client/src/components/organisms/Header/style.ts
  client/src/pages/Login/index.tsx
  client/src/pages/Login/style.ts
  client/src/pages/Login/templates/index.tsx
  client/src/pages/Login/templates/style.ts
  client/src/pages/Page/templates/index.stories.tsx
  client/src/pages/Page/templates/index.tsx
  client/src/pages/Page/templates/style.ts
Labels: frontend, page

#39 #12 [PR] Oauth API 제작
  .travis.yml
  server/.env
  server/src/config/oauth_google.ts
  server/src/config/server_url.ts
  server/src/routes/api/auth/index.ts
  server/src/services/passport.ts
Labels: backend, feature

#84 [PR] 회원가입페이지 '초안' 개발
  client/src/App.tsx
  client/src/commons/constants/string.ts
  client/src/components/atoms/Btn/index.stories.tsx
  client/src/components/atoms/Btn/index.tsx
  client/src/components/atoms/Input/index.stories.tsx
  client/src/components/atoms/Input/index.tsx
  client/src/components/molecules/FormInput/index.stories.tsx
  client/src/components/molecules/FormInput/index.tsx
  client/src/components/molecules/IconBtn/index.tsx
  client/src/components/molecules/IconBtn/style.ts
  client/src/components/organisms/SignUpForm/index.stories.tsx
  client/src/components/organisms/SignUpForm/index.tsx
  client/src/components/organisms/SignUpForm/style.ts
  client/src/pages/Login/index.tsx
  client/src/pages/SignUp/index.stories.tsx
  client/src/pages/SignUp/index.tsx
  client/src/pages/SignUp/template/index.tsx
  client/src/pages/SignUp/template/style.ts
Labels: frontend, page

#94 [PR] Base Component Test 작성
  client/package.json
  client/src/components/atoms/Btn/__snapshots__/index.spec.tsx.snap
  client/src/components/atoms/Btn/index.spec.tsx
  client/src/components/atoms/Divider/__snapshots__/index.spec.tsx.snap
  client/src/components/atoms/Divider/index.spec.tsx
  client/src/components/atoms/Icon/__snapshots__/index.spec.tsx.snap
  client/src/components/atoms/Icon/index.spec.tsx
  client/src/components/atoms/Input/__snapshots__/index.spec.tsx.snap
  client/src/components/atoms/Input/index.spec.tsx
  client/src/components/atoms/Label/__snapshots__/index.spec.tsx.snap
  client/src/components/atoms/Label/index.spec.tsx
  client/src/setupTests.ts
  yarn.lock
Labels: frontend, test

#99 [PR] State 관리방법을 적용한 회원가입 페이지를 만듦 / BaseComponent에 대한 모양을 변경함.
  client/src/commons/constants/apis.ts
  client/src/components/atoms/Btn/index.tsx
  client/src/components/atoms/Divider/index.tsx
  client/src/components/atoms/Icon/index.tsx
  client/src/components/atoms/Input/index.tsx
  client/src/components/atoms/Label/index.tsx
  client/src/components/molecules/Card/index.tsx
  client/src/components/molecules/FormInput/index.stories.tsx
  client/src/components/molecules/FormInput/index.tsx
  client/src/components/organisms/SignUpForm/index.stories.tsx
  client/src/components/organisms/SignUpForm/index.tsx
  client/src/pages/SignUp/index.tsx
Labels: component, frontend

#105 [PR] Axios 모듈 추가
  client/package.json
  yarn.lock
Labels: frontend

#106 [PR] GET /api/events
  .gitignore
  server/bin/migrate.ts
  server/bin/seed.ts
  server/bin/www.ts
  server/src/app.ts
  server/src/routes/api/events/controllers/index.ts
  server/src/routes/api/events/index.ts
  server/src/routes/api/events/validators/getEvents.ts
  server/src/routes/api/events/validators/index.ts
  server/src/utils/errorHandler.ts
  server/src/utils/passport.ts
  server/src/utils/sequelize.ts
  server/test/api/event.spec.ts
  server/test/db/seed.spec.ts
Labels: api, backend, feature

#115 [PR] Migration Bug 수정 / Travis에서 일어나던 오류 수정
  client/src/components/atoms/Input/__snapshots__/index.spec.tsx.snap
  client/src/components/atoms/Input/index.spec.tsx
  server/src/models/Event.ts
  server/src/models/Order.ts
  server/src/models/OrderTicket.ts
  server/src/models/TicketType.ts
  server/src/models/User.ts
  server/test/db/model.spec.ts
Labels: backend, frontend, test

#113 [PR] server .env file template
  .gitignore
  server/.env.template
Labels: backend

#114 [PR] Server app port 환경변수화
  .travis.yml
  server/.env.template
  server/bin/www.ts
Labels: backend

#122 [PR] package.json 및 yarn.lock 정리
  client/package.json
  package.json
  server/package.json
  yarn.lock
Labels: backend, frontend

#126 [PR] pre-push git hook 에서 test 가 돌도록 함
  client/package.json
  package.json
Labels: test

#124 [PR] regenerate yarn.lock
  yarn.lock
Labels: backend, frontend

#127 [PR] useFetch 작성
  client/src/hooks/base/useFetch/index.spec.tsx
  client/src/hooks/base/useFetch/index.ts
  client/src/hooks/index.ts
  client/src/setupTests.ts
Labels: feature, frontend

#128 [PR] getEvents service
  server/db_seeds/events.json
  server/db_seeds/ticketTypes.json
  server/src/services/events.ts
  server/test/db/__snapshots__/seed.spec.ts.snap
Labels: api, backend, feature

#109 [PR] oauth와 토큰, 회원가입과 쿠키 초기작업 / Store, View 분리
  client/package.json
  client/src/commons/constants/apis.ts
  client/src/components/atoms/Input/index.spec.tsx
  client/src/components/atoms/Input/index.tsx
  client/src/components/molecules/FormInput/index.tsx
  client/src/components/organisms/SignUpForm/index.stories.tsx
  client/src/components/organisms/SignUpForm/index.tsx
  client/src/hooks/base/useStateReduter/index.ts
  client/src/pages/SignUp/index.tsx
  client/src/pages/SignUp/store.tsx
  client/src/pages/SignUp/view.tsx
  client/src/types/Actions.ts
  client/src/types/CustomHooks.ts
  client/src/types/States.ts
  client/src/utils/validateSignUpForms.spec.ts
  client/src/utils/validateSignUpForms.ts
  server/bin/www.ts
  server/package.json
  server/src/app.ts
  server/src/routes/api/auth/controllers/authCallback.ts
  server/src/routes/api/auth/controllers/authRequest.ts
  server/src/routes/api/auth/controllers/authToken.ts
  server/src/routes/api/auth/controllers/index.ts
  server/src/routes/api/auth/index.ts
  server/src/routes/api/users/controllers/createUser.ts
  server/src/routes/api/users/controllers/index.ts
  server/src/routes/api/users/index.ts
  server/src/services/index.ts
  server/src/services/users.ts
  server/src/utils/jwt.ts
  server/src/utils/passport.ts
  server/test/template.spec.ts
  yarn.lock
Labels: api, backend, component, feature, frontend

#111 [PR] client dotenv 추가
  .gitignore
  client/.storybook/webpack.config.js
  client/package.json
Labels: frontend

#132 [PR] fix events service wrong field name
  server/src/services/events.ts
Labels: api, backend, bug

#133 [PR] remove pre-push test hook
  package.json
Labels: 🌑 Backend, 🌕 Frontend

#135 [PR] fix get event api
  server/src/routes/api/events/controllers/getEvents.ts
  server/src/routes/api/events/validators/getEvents.ts
  server/src/services/events.ts
  server/test/api/event.spec.ts
Labels: 🌑 Backend, 🐛 BUG, 🕊 API, 🚨 ASAP

#100 [1차 PR] EventDetailPage (이벤트 상세 페이지)
  client/package.json
  client/src/App.tsx
  client/src/assets/img/calendar-black.svg
  client/src/assets/img/calendar-gray.svg
  client/src/assets/img/check-black.svg
  client/src/assets/img/check-gray.svg
  client/src/assets/img/external-link-black.svg
  client/src/assets/img/external-link-colored.svg
  client/src/assets/img/multiple-users-silhouette-gray.svg
  client/src/assets/img/multiple-users-silhouette.svg
  client/src/assets/img/pin.svg
  client/src/commons/constants/routes.ts
  client/src/commons/style/GlobalStyle.ts
  client/src/components/atoms/Btn/index.stories.tsx
  client/src/components/atoms/Btn/style.ts
  client/src/components/atoms/Divider/index.tsx
  client/src/components/atoms/GoogleMap/index.stories.tsx
  client/src/components/atoms/GoogleMap/index.tsx
  client/src/components/atoms/GoogleMap/style.ts
  client/src/components/atoms/Icon/__snapshots__/index.spec.tsx.snap
  client/src/components/atoms/Icon/index.spec.tsx
  client/src/components/atoms/Icon/index.stories.tsx
  client/src/components/atoms/Icon/index.tsx
  client/src/components/atoms/Icon/style.ts
  client/src/components/atoms/Input/index.stories.tsx
  client/src/components/molecules/IconBtn/__snapshots__/index.spec.tsx.snap
  client/src/components/molecules/IconBtn/index.spec.tsx
  client/src/components/molecules/IconBtn/index.stories.tsx
  client/src/components/molecules/IconBtn/index.tsx
  client/src/components/molecules/IconBtn/style.ts
  client/src/hooks/base/useFetch/index.ts
  client/src/pages/BasicPage/templates/index.stories.tsx
  client/src/pages/BasicPage/templates/index.tsx
  client/src/pages/BasicPage/templates/style.ts
  client/src/pages/EventDetail/index.tsx
  client/src/pages/EventDetail/store.tsx
  client/src/pages/EventDetail/template/index.stories.tsx
  client/src/pages/EventDetail/template/index.tsx
  client/src/pages/EventDetail/template/style.ts
  client/src/pages/EventDetail/view.tsx
  client/src/pages/Login/index.tsx
  client/src/types/Data.ts
  client/src/types/States.ts
  yarn.lock
Labels: 🌕 Frontend, 😏 Page

#98 [PR] 메인페이지 컴포넌트 작성
  client/package.json
  client/src/App.tsx
  client/src/commons/constants/number.ts
  client/src/components/molecules/Card/index.stories.tsx
  client/src/components/molecules/Card/index.tsx
  client/src/components/molecules/Card/style.ts
  client/src/components/organisms/CardGrid/index.stories.tsx
  client/src/components/organisms/CardGrid/index.tsx
  client/src/components/organisms/CardGrid/style.ts
  client/src/components/organisms/Header/index.tsx
  client/src/components/organisms/MainBanner/index.stories.tsx
  client/src/components/organisms/MainBanner/index.tsx
  client/src/components/organisms/MainBanner/style.ts
  client/src/hooks/base/useIntersect/index.ts
  client/src/hooks/index.ts
  client/src/pages/Main/index.stories.tsx
  client/src/pages/Main/index.tsx
  client/src/pages/Main/template/index.tsx
  client/src/pages/Main/template/style.ts
  client/src/pages/SignUp/store.tsx
  client/src/setupTests.ts
  client/src/types/Event.ts
  server/src/services/events.ts
  yarn.lock
Labels: ✨ Feature, 🌕 Frontend, 😏 Page, 🧩 Component

#139 [PR] 이벤트 디테일 API
  server/src/routes/api/events/controllers/getEvent.ts
  server/src/routes/api/events/controllers/index.ts
  server/src/routes/api/events/index.ts
  server/src/services/events.ts
Labels: ✨ Feature, 🌑 Backend, 🕊 API, 🚨 ASAP

#141 [PR] fix: hottest fix
  client/src/App.tsx
  yarn.lock
Labels: 🐛 BUG, 🚨 ASAP
